### ISSUE TITLE
Tracking issue for Chrome APIs

### ISSUE THREAD

**Issue by sentialx** [sentialx/electron-extensions#14]
Currently supported APIs:
- [ ] [`tabs`](https://developer.chrome.com/extensions/tabs)
  - [x] `onCreated`
  - [x] `onUpdated`
  - [x] `onActivated`
  - [ ] `onRemoved`
  - [ ] `detectLanguage`
  - [ ] `getZoom`
  - [ ] `setZoom`
  - [x] `executeScript`
  - [x] `insertCSS`
  - [x] `get`
  - [x] `getCurrent`
  - [x] `query`
  - [x] `create`
  - [x] `sendMessage`
- [ ] [`webNavigation`](https://developer.chrome.com/extensions/webNavigation)
  - [x] `onBeforeNavigate`
  - [x] `onCommitted`
  - [x] `onDOMContentLoaded`
  - [x] `onCompleted`
  - [x] `onCreatedNavigationTarget`
  - [ ] `onReferenceFragmentUpdated`
  - [ ] `onTabReplaced`
  - [ ] `onHistoryStateUpdated`
- [ ] [`webRequest`](https://developer.chrome.com/extensions/webRequest)
  - [x] `onBeforeRequest`
  - [x] `onBeforeSendHeaders`
  - [x] `onHeadersReceived`
  - [x] `onSendHeaders`
  - [ ] `onResponseStarted`
  - [ ] `onBeforeRedirect`
  - [x] `onCompleted`
  - [x] `onErrorOccurred`
- [ ] [`runtime`](https://developer.chrome.com/extensions/runtime)
  - [x] `id`
  - [x] `getManifest`
  - [x] `getURL`
  - [x] `reload`
  - [x] `connect`
  - [x] `onConnect`
  - [ ] `lastError`
  - [ ] `getPlatformInfo`
  - [ ] `onInstalled`
  - [x] `onMessage`
  - [x] `sendMessage`
  - [ ] `OnInstalledReason`
- [ ] [`storage`](https://developer.chrome.com/extensions/storage)
  - [x] `local`
  - [ ] `sync`
  - [x] `managed`
  - [ ] `onChanged`
- [ ] [`i18n`](https://developer.chrome.com/extensions/i18n)
  - [ ] `getAcceptLanguages `
  - [x] `getMessage`
  - [ ] `getUILanguage`
  - [ ] `detectLanguage`
- [ ] [`alarms`](https://developer.chrome.com/extensions/alarms)
- [ ] [`extension`](https://developer.chrome.com/extensions/extension)
- [ ] [`browserAction`](https://developer.chrome.com/extensions/browserAction)
  - [x] `setBadgeText`
  - [x] `onClicked`
  - [ ] `setBadgeBackgroundColor`
  - [ ] `setIcon`
- [ ] [`management`](https://developer.chrome.com/extensions/management)
  - [ ] `get`
  - [ ] `onInstalled`
  - [ ] `onUninstalled`
  - [ ] `uninstallSelf`
- [ ] [`downloads`](https://developer.chrome.com/extensions/downloads)
  - [ ] `search`
  - [ ] `erase`
  - [ ] `download`

**Comment by RangerMauve** [comment]
Would PRs for APIs be welcome? I'd be interested in contributing the Chrome Sockets API for UDP and TCP sockets.

**Comment by sentialx** [comment]
Yes of course!
